# site settings
title: Empowering
subtitle: Motherland
permalink: /:title/
email: blabla@gmail.com
description: Give some kind of description.
baseurl: ""
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Kigali
zip_code: xxxx
country: Rwanda
phone: +250 (xxx) xxx-xxxx

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
#500px_url:
#facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
